"""
Generates `mfcc_frontend.h`: a dependency-free C/C++ implementation of the
exact MFCC front-end in app.services.preprocessing.compute_mfcc, so audio
models get the same features on the microcontroller as in training.

The mel filterbank and DCT matrix are emitted as constant tables (computed
with the same code the backend uses); the FFT and window are computed at
runtime. Verified against the Python implementation in
tests/test_mfcc_codegen.py by compiling the header with a host C++ compiler.
"""

from typing import List

import numpy as np

from app.services import preprocessing


def _floats(values, per_line: int = 8) -> str:
    vals = [f"{float(v):.9g}f" for v in np.asarray(values).reshape(-1)]
    lines = [", ".join(vals[i:i + per_line]) for i in range(0, len(vals), per_line)]
    return ",\n  ".join(lines)


def _ints(values: List[int], per_line: int = 16) -> str:
    vals = [str(int(v)) for v in values]
    return ",\n  ".join(", ".join(vals[i:i + per_line]) for i in range(0, len(vals), per_line))


def generate_mfcc_header(task: str, n_mfcc: int, n_frames: int) -> str:
    p = preprocessing.audio_params(task, n_mfcc)
    n_fft, hop, n_mels = int(p["n_fft"]), int(p["hop_length"]), int(p["n_mels"])
    n_bins = n_fft // 2 + 1
    mel = preprocessing.mel_filterbank(int(p["sample_rate"]), n_fft, n_mels, float(p["fmin"]), float(p["fmax"]))
    dct = preprocessing.dct_matrix(n_mfcc, n_mels)

    starts, lens, offsets, weights = [], [], [], []
    for m in range(n_mels):
        nz = np.nonzero(mel[m])[0]
        s, e = (int(nz[0]), int(nz[-1]) + 1) if len(nz) else (0, 0)
        starts.append(s)
        lens.append(e - s)
        offsets.append(len(weights))
        weights.extend(mel[m, s:e].tolist())

    computed_frames = int(p["n_frames"])
    return f"""// mfcc_frontend.h - generated by EdgeCraft AI
// Bit-for-bit port of the training-time MFCC front-end:
//   16 kHz mono, {p['duration']} s clip, periodic Hann window, {n_fft}-point FFT,
//   hop {hop}, {n_mels} mel bands ({p['fmin']:.0f}-{p['fmax']:.0f} Hz, Slaney),
//   10*log10 power clamped to max-{p['top_db']:.0f} dB, orthonormal DCT-II,
//   then per-clip z-score normalisation.
// Feed it float samples in [-1, 1] (the absolute scale does not matter:
// the log + z-score steps cancel any constant gain).
#pragma once
#include <math.h>
#include <stdint.h>
#include <string.h>

#define MFCC_SAMPLE_RATE {int(p['sample_rate'])}
#define MFCC_N_SAMPLES   {int(p['n_samples'])}
#define MFCC_N_FFT       {n_fft}
#define MFCC_HOP         {hop}
#define MFCC_N_MELS      {n_mels}
#define MFCC_N_MFCC      {n_mfcc}
#define MFCC_N_FRAMES    {computed_frames}
#define MFCC_OUT_FRAMES  {n_frames}   // model's time axis (padded / truncated)
#define MFCC_TOP_DB      {float(p['top_db']):.1f}f

static const uint16_t kMelStart[MFCC_N_MELS] = {{
  {_ints(starts)}
}};
static const uint16_t kMelLen[MFCC_N_MELS] = {{
  {_ints(lens)}
}};
static const uint16_t kMelOffset[MFCC_N_MELS] = {{
  {_ints(offsets)}
}};
static const float kMelWeights[{len(weights)}] = {{
  {_floats(weights)}
}};
static const float kDct[MFCC_N_MFCC * MFCC_N_MELS] = {{
  {_floats(dct)}
}};

static float g_mfcc_re[MFCC_N_FFT];
static float g_mfcc_im[MFCC_N_FFT];
static float g_mfcc_window[MFCC_N_FFT];
static float g_mfcc_logmel[MFCC_N_FRAMES * MFCC_N_MELS];
static bool  g_mfcc_ready = false;

static void mfcc_init() {{
  for (int i = 0; i < MFCC_N_FFT; i++) {{
    g_mfcc_window[i] = 0.5f - 0.5f * cosf(2.0f * (float)M_PI * i / MFCC_N_FFT);
  }}
  g_mfcc_ready = true;
}}

// In-place iterative radix-2 complex FFT (MFCC_N_FFT must be a power of 2).
static void mfcc_fft(float* re, float* im) {{
  const int n = MFCC_N_FFT;
  for (int i = 1, j = 0; i < n; i++) {{
    int bit = n >> 1;
    for (; j & bit; bit >>= 1) j ^= bit;
    j ^= bit;
    if (i < j) {{
      float t = re[i]; re[i] = re[j]; re[j] = t;
      t = im[i]; im[i] = im[j]; im[j] = t;
    }}
  }}
  for (int len = 2; len <= n; len <<= 1) {{
    const float ang = -2.0f * (float)M_PI / len;
    for (int i = 0; i < n; i += len) {{
      for (int k = 0; k < len / 2; k++) {{
        const float wr = cosf(ang * k), wi = sinf(ang * k);
        const int a = i + k, b = i + k + len / 2;
        const float xr = re[b] * wr - im[b] * wi;
        const float xi = re[b] * wi + im[b] * wr;
        re[b] = re[a] - xr; im[b] = im[a] - xi;
        re[a] += xr;        im[a] += xi;
      }}
    }}
  }}
}}

// audio: MFCC_N_SAMPLES floats. out: MFCC_N_MFCC * MFCC_OUT_FRAMES floats,
// laid out [coefficient][frame] - the model's (n_mfcc, frames, 1) input.
static void mfcc_compute(const float* audio, float* out) {{
  if (!g_mfcc_ready) mfcc_init();
  float max_db = -1e30f;
  for (int f = 0; f < MFCC_N_FRAMES; f++) {{
    const float* frame = audio + f * MFCC_HOP;
    for (int i = 0; i < MFCC_N_FFT; i++) {{
      g_mfcc_re[i] = frame[i] * g_mfcc_window[i];
      g_mfcc_im[i] = 0.0f;
    }}
    mfcc_fft(g_mfcc_re, g_mfcc_im);
    for (int m = 0; m < MFCC_N_MELS; m++) {{
      float acc = 0.0f;
      const float* w = kMelWeights + kMelOffset[m];
      for (int k = 0; k < kMelLen[m]; k++) {{
        const int bin = kMelStart[m] + k;
        acc += w[k] * (g_mfcc_re[bin] * g_mfcc_re[bin] + g_mfcc_im[bin] * g_mfcc_im[bin]);
      }}
      float db = 10.0f * log10f(acc > 1e-10f ? acc : 1e-10f);
      g_mfcc_logmel[f * MFCC_N_MELS + m] = db;
      if (db > max_db) max_db = db;
    }}
  }}
  const float floor_db = max_db - MFCC_TOP_DB;
  for (int i = 0; i < MFCC_N_FRAMES * MFCC_N_MELS; i++) {{
    if (g_mfcc_logmel[i] < floor_db) g_mfcc_logmel[i] = floor_db;
  }}

  double sum = 0.0, sq = 0.0;
  for (int c = 0; c < MFCC_N_MFCC; c++) {{
    for (int f = 0; f < MFCC_N_FRAMES; f++) {{
      float acc = 0.0f;
      const float* row = kDct + c * MFCC_N_MELS;
      const float* lm = g_mfcc_logmel + f * MFCC_N_MELS;
      for (int m = 0; m < MFCC_N_MELS; m++) acc += row[m] * lm[m];
      if (f < MFCC_OUT_FRAMES) out[c * MFCC_OUT_FRAMES + f] = acc;
      sum += acc;
      sq += (double)acc * acc;
    }}
  }}
  const double count = (double)MFCC_N_MFCC * MFCC_N_FRAMES;
  const double mean = sum / count;
  double var = sq / count - mean * mean;
  if (var < 0) var = 0;
  const float inv_std = 1.0f / ((float)sqrt(var) + 1e-6f);
  for (int c = 0; c < MFCC_N_MFCC; c++) {{
    for (int f = 0; f < MFCC_OUT_FRAMES; f++) {{
      float* v = &out[c * MFCC_OUT_FRAMES + f];
      *v = (f < MFCC_N_FRAMES) ? (float)((*v - mean) * inv_std) : 0.0f;
    }}
  }}
}}
"""
